# Generated by Django 6.0.3 on 2026-03-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_library_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(blank=True, max_length=255)),
                ('cover_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('want', 'Want to Read'), ('completed', 'Completed')], default='want', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
