# Generated by Django 6.0.3 on 2026-03-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages_read',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
