# Generated by Django 6.0.3 on 2026-03-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_author_book_description_book_trending_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('want', 'Want to Read'), ('reading', 'Currently Reading'), ('completed', 'Completed')], default='want', max_length=20),
        ),
    ]
